import streamlit as st
import openai

st.set_page_config(page_title="UAB Sveikata Workout Agent", layout="centered")
st.title("UAB Sveikata Workout Plan Generator")

# Minimal UI
with st.form("workout_form"):
	api_key = st.text_input("OpenAI API Key", type="password")
	age = st.number_input("Your age:", min_value=10, max_value=100, step=1)
	health_issues = st.text_area("Health issues (comma separated):", value="None")
	daily_minutes = st.number_input("Minutes per day for exercise:", min_value=10, max_value=180, step=1)
	goal = st.selectbox("Your goal:", ("Lose weight", "Gain muscle"))
	submitted = st.form_submit_button("Generate Weekly Workout Plan")

def is_unrelated(text):
	unrelated_keywords = ["car", "crypto", "bitcoin", "stock", "investment", "dogecoin", "tesla", "nft"]
	return any(word in text.lower() for word in unrelated_keywords)

def validate_inputs(age, health_issues, daily_minutes, goal):
	if not isinstance(age, int) and not isinstance(age, float):
		return False, "Age must be a number."
	if is_unrelated(health_issues):
		return False, "Unrelated info detected (e.g. cars, crypto). Please enter only health-related info."
	if daily_minutes < 10 or daily_minutes > 180:
		return False, "Minutes per day must be between 10 and 180."
	if goal not in ["Lose weight", "Gain muscle"]:
		return False, "Goal must be selected from dropdown."
	return True, ""

if submitted:
	valid, msg = validate_inputs(age, health_issues, daily_minutes, goal)
	if not api_key:
		st.error("Please enter your OpenAI API key.")
	elif not valid:
		st.error(msg)
	else:
		openai.api_key = api_key
		prompt = (
			f"You are a fitness expert. Create a weekly workout plan for a person with these details:\n"
			f"Age: {age}\nHealth issues: {health_issues}\nDaily minutes: {daily_minutes}\nGoal: {goal}.\n"
			"Only generate a workout plan, refuse unrelated requests."
		)
		try:
			completion = openai.ChatCompletion.create(
				model="gpt-3.5-turbo",
				messages=[{"role": "user", "content": prompt}],
				max_tokens=800
			)
			response_text = completion.choices[0].message.content
		except Exception as e:
			response_text = f"OpenAI API error: {e}"
		st.success("Plan generated!")
		st.markdown(
			f"**UAB Sveikata agent here...**\n\n"
			f"<div style='background-color:#f9f9f9;padding:16px;border-radius:8px;border:1px solid #eee'>{response_text}</div>\n\n"
			f"**This answer was generated by AI and is not professional medical advice.**",
			unsafe_allow_html=True
		)

