# Improved Streamlit app with explicit API key form/button and safer session handling
import os
import json
import urllib.request
import urllib.error
import streamlit as st

# Page configuration
st.set_page_config(page_title="UAB Sveikata - Exercise Planner", layout="centered")

st.title("💪 UAB Sveikata - Weekly Exercise Plan Generator")
st.markdown("Get personalized weekly exercise recommendations powered by AI")

# -- Session state defaults
if "openai_api_key" not in st.session_state:
    st.session_state.openai_api_key = ""

# API Key form (explicit submit) so users can paste and then click Set
st.markdown("---")
st.subheader("🔐 API Configuration")
with st.form("api_key_form"):
    key_input = st.text_input(
        "Enter your OpenAI API key:",
        value=st.session_state.get("openai_api_key", ""),
        type="password",
        placeholder="sk-...",
        help="Your API key is kept in session only and not stored on disk."
    )
    set_key = st.form_submit_button("Set API key")

if set_key:
    if key_input and key_input.strip():
        st.session_state.openai_api_key = key_input.strip()
        st.success("API key set for this session")
    else:
        st.session_state.openai_api_key = ""
        st.warning("Empty key — API key not set")

if st.session_state.openai_api_key:
    st.info("API key is set. You can now generate a plan.")
    if st.button("Clear API key"):
        st.session_state.openai_api_key = ""
        st.experimental_rerun()
else:
    st.warning("⚠️ Please set your OpenAI API key above (paste then press 'Set API key').")

# Input form
st.markdown("---")
st.subheader("📋 Your Information")

col1, col2 = st.columns(2)

with col1:
    age = st.number_input(
        "Age:",
        min_value=1,
        max_value=120,
        value=30,
        step=1,
        help="Enter your age in years"
    )

with col2:
    minutes_per_day = st.number_input(
        "Minutes per day for exercise:",
        min_value=5,
        max_value=240,
        value=30,
        step=5,
        help="How many minutes per day can you exercise?"
    )

goal = st.selectbox(
    "Exercise Goal:",
    ["Lose weight", "Gain muscle"],
    help="Select your primary fitness goal"
)

health_issues = st.text_area(
    "Known health issues (optional):",
    placeholder="e.g., lower back pain, asthma, etc.",
    height=80,
    help="Describe any health conditions the AI should consider"
)

# List of unrelated topics to reject
unrelated_topics = ["car", "crypto", "bitcoin", "ethereum", "politics", "political", "government"]

def is_unrelated_topic(text):
    """Check if text contains unrelated topics"""
    if not text:
        return False
    text_lower = text.lower()
    return any(topic in text_lower for topic in unrelated_topics)

# Generate plan button
if st.button("🚀 Generate My Exercise Plan", type="primary"):
    # Validate inputs
    if not age or age < 1:
        st.error("❌ Please enter a valid age")
        st.stop()
    
    if not minutes_per_day or minutes_per_day < 5:
        st.error("❌ Please enter at least 5 minutes per day")
        st.stop()
    
    if goal not in ["Lose weight", "Gain muscle"]:
        st.error("❌ Please select a valid goal")
        st.stop()
    
    if is_unrelated_topic(health_issues):
        st.error("❌ Please only describe health-related issues. Topics like cars, crypto, and politics are not relevant to exercise planning.")
        st.stop()
    
    # Build the prompt
    health_info = f"Known health issues: {health_issues}" if health_issues else "No known health issues"
    
    prompt = f"""You are a professional fitness advisor for UAB Sveikata. Create a detailed weekly exercise plan based on the following information:

- Age: {age} years old
- Primary Goal: {goal}
- Available time per day: {minutes_per_day} minutes
- {health_info}

Please provide a comprehensive weekly exercise plan that:
1. Is appropriate for the person's age and fitness goal
2. Fits within their daily time constraints
3. Takes into account any health issues mentioned
4. Includes specific exercises with sets/reps or duration
5. Provides a balanced routine (mix of cardio, strength, flexibility)
6. Includes rest days
7. Offers modifications for safety

Start your response with: "UAB Sveikata agent here…"
End your response with: "This answer was generated by AI and is not professional medical advice."

Provide clear, actionable advice."""
    
    # Show loading message
    with st.spinner("🔄 Generating your personalized exercise plan..."):
        try:
            # Ensure we have an API key in session
            if not st.session_state.openai_api_key:
                st.error("No API key found in session. Please set it using the 'Set API key' button above.")
                st.stop()

            # Use the OpenAI REST API directly with the session API key to avoid
            # relying on the installed OpenAI Python client (which can fail in
            # some environments with unexpected kwargs like 'proxies'). This
            # uses only the Python standard library (urllib) so no extra deps.
            api_key = st.session_state.openai_api_key
            url = "https://api.openai.com/v1/chat/completions"
            headers = {
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            }
            payload = {
                "model": "gpt-4o-mini",
                "messages": [
                    {"role": "system", "content": "You are a professional fitness advisor. Provide safe, practical exercise recommendations."},
                    {"role": "user", "content": prompt},
                ],
                "temperature": 0.7,
                "max_tokens": 1500,
            }

            data = json.dumps(payload).encode("utf-8")
            req = urllib.request.Request(url, data=data, headers=headers, method="POST")
            try:
                with urllib.request.urlopen(req, timeout=30) as resp:
                    resp_text = resp.read().decode("utf-8")
                    response = json.loads(resp_text)
            except urllib.error.HTTPError as he:
                err_text = he.read().decode("utf-8")
                raise RuntimeError(f"OpenAI API HTTP error: {he.code} {err_text}")
            except Exception as ex:
                raise RuntimeError(f"OpenAI API request failed: {ex}")

            # Extract content safely from the response
            try:
                plan = response["choices"][0]["message"]["content"]
            except Exception:
                # Fallbacks for other shapes
                try:
                    plan = response.choices[0].message.content
                except Exception:
                    plan = getattr(response, "text", "") or str(response)

            # Verify required start and end texts
            if "UAB Sveikata agent here" not in plan:
                plan = "UAB Sveikata agent here…\n\n" + plan

            if "This answer was generated by AI and is not professional medical advice." not in plan:
                plan = plan + "\n\nThis answer was generated by AI and is not professional medical advice."

            # Display the plan
            st.markdown("---")
            st.subheader("✅ Your Personalized Weekly Exercise Plan")
            st.markdown(plan)

            # Display metadata
            st.markdown("---")
            st.markdown("### 📊 Plan Details")
            col1, col2, col3, col4 = st.columns(4)
            col1.metric("Age", f"{age} years")
            col2.metric("Daily Time", f"{minutes_per_day} min")
            col3.metric("Goal", goal)
            col4.metric("Model", "GPT-4o-mini")

        except Exception as e:
            err_str = str(e)
            if "401" in err_str or "invalid" in err_str.lower() or "unauthorized" in err_str.lower():
                st.error("❌ Authentication error: the API key appears invalid. Re-enter your key and press 'Set API key'.")
            elif "rate limit" in err_str.lower():
                st.error("❌ Rate limit or quota exceeded. Check your OpenAI account usage.")
            else:
                st.error(f"❌ Error generating plan: {err_str}")
            st.info("If this persists, verify your API key at https://platform.openai.com/account/api-keys and try again.")

# Footer
st.markdown("---")
st.markdown("""
<div style='text-align: center; color: gray; font-size: 12px;'>
    <p>UAB Sveikata Exercise Planner | Powered by OpenAI</p>
    <p>⚠️ This app provides AI-generated fitness suggestions only. Consult a healthcare professional before starting any exercise program.</p>
</div>
""", unsafe_allow_html=True)
